region: eu-west-1
stacks:
 python-docker-hello-world-webapp:
   template-url: templates/ecs-simple-webapp.yml
   timeout: 1200
   parameters:
     dnsDomain: 'deploy.wolke.is'
     vpcId: "|Ref|vpc.id"
     subnetIds: "|Ref|vpc.subnets"
     amiId: ami-6b12271c
     dockerImageVersion: 0.2.3
     dockerAppImage: immobilienscout24/python-docker-hello-world-webapp
     sshKeyName: aws-deployment
     InstanceType: t2.small
     LogStreamName: aws-deployment
     dockerContainerName: python-docker-hello-world-webapp

